apiVersion: batch/v1
kind: Job
metadata:
  name: download-ubuntu-jammy
  namespace: tink-system
spec:
  template:
    spec:
      containers:
        - name: download-ubuntu-jammy
          image: bash:5.2.2
          command: ["/script/entrypoint.sh"]
          args:
            [
              "https://cloud-images.ubuntu.com/daily/server/jammy/current/jammy-server-cloudimg-amd64.img",
              "/output",
            ]
          volumeMounts:
            - mountPath: /output
              name: hook-artifacts
            - mountPath: /script
              name: configmap-volume
      restartPolicy: OnFailure
      volumes:
        - name: hook-artifacts
          hostPath:
            path: /opt/hook
            type: DirectoryOrCreate
        - name: configmap-volume
          configMap:
            defaultMode: 0700
            name: download-ubuntu-jammy
